[project]
name = "2026-p1-tom-strooper"
version = "0.1.0"
description = ""
authors = [
    {name = "Tom-Strooper",email = "s4744920@student.uq.edu.au"}
]
readme = "README.md"
requires-python = ">=3.12"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
flask = "^3.1.3"
